#!/bin/sh
#set -ex

uwsgi --ini /etc/uwsgi.ini &
celery beat -l info -f /tmp/celery_beat.log --scheduler djcelery.schedulers:DatabaseScheduler $@ &
celery flower -l info -f /tmp/celery_flower.log --address=0.0.0.0 --port=5555 $@ &

exec celery worker -l info -f /tmp/celery_worker.log $@
